name: Publish Repostat to PyPI
on:
  push:
    tags:
      - v2.*

jobs:
  build-n-publish:

    name: Build and publish Python distributions to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7

    - name: Build a binary wheel and a source tarball
      run: |
        python -m pip install --upgrade setuptools wheel --user
        python setup.py sdist bdist_wheel

    - name: Publish to Test PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.test_pypi_password }}
        repository_url: https://test.pypi.org/legacy/

    - name: Install repostat from Test PyPi
      run: |
        python -m pip install --index-url https://test.pypi.org/simple/ repostat-app
        repostat --help

    # TODO: uncomment when tested on Test PyPi
    #    - name: Publish distribution 📦 to PyPI
    # FIXME: adjust to regexp vx.x.x
    #      if: startsWith(github.event.ref, 'refs/tags')
    #      uses: pypa/gh-action-pypi-publish@master
    #      with:
    #        password: ${{ secrets.pypi_password }}